# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZDMPlatform' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZDMPlatform
  pod 'ZohoDeskPortalAPIKit', :git => 'https://zgit.csez.zohocorpin.com/ZohoDeskMobile/asap-ios-with-platform.git', :branch => 'multi_template_platform'
  pod 'ZohoDeskPortalConfiguration', :git => 'https://zgit.csez.zohocorpin.com/ZohoDeskMobile/asap-ios-with-platform.git', :branch => 'multi_template_platform'
  pod 'ZohoDeskPortalTicket', :git => 'https://zgit.csez.zohocorpin.com/ZohoDeskMobile/asap-ios-with-platform.git', :branch => 'multi_template_platform'
  
  pod 'ZohoDeskPlatformDataBridge', :git => 'https://zgit.csez.zohocorpin.com/ZohoDeskMobile/desk-platform-sdk-ios.git', :branch => 'lakshmi_binder_simplification'
  pod 'ZohoDeskPlatformUIKit/ZPMediaPicker', :git => 'https://zgit.csez.zohocorpin.com/ZohoDeskMobile/desk-platform-sdk-ios.git', :branch => 'lakshmi_binder_simplification'
  
  pod 'ZDMediaPickerSDK',  :git => 'https://git.csez.zohocorpin.com/ZohoDeskMobile/zdmediapicker.git'
  
  pod 'ZPComponents', :git => 'https://zgit.csez.zohocorpin.com/ZohoDeskMobile/zpcomponents.git', :branch => 'Zoholics_2023'

end
